class CountryInfo {
  final String name;
  final String flag;
  final String code;
  final String dialCode;

  const CountryInfo({
    required this.name,
    required this.flag,
    required this.code,
    required this.dialCode,
  });
}

const List<CountryInfo> countries = [
  CountryInfo(name: 'Afghanistan', flag: '🇦🇫', code: 'AF', dialCode: '+93'),
  CountryInfo(name: 'Albania', flag: '🇦🇱', code: 'AL', dialCode: '+355'),
  CountryInfo(name: 'Algeria', flag: '🇩🇿', code: 'DZ', dialCode: '+213'),
  CountryInfo(name: 'Andorra', flag: '🇦🇩', code: 'AD', dialCode: '+376'),
  CountryInfo(name: 'Angola', flag: '🇦🇴', code: 'AO', dialCode: '+244'),
  CountryInfo(name: 'Anguilla', flag: '🇦🇮', code: 'AI', dialCode: '+1'),
  CountryInfo(name: 'Antigua & Barbuda', flag: '🇦🇬', code: 'AG', dialCode: '+1'),
  CountryInfo(name: 'Argentina', flag: '🇦🇷', code: 'AR', dialCode: '+54'),
  CountryInfo(name: 'Armenia', flag: '🇦🇲', code: 'AM', dialCode: '+374'),
  CountryInfo(name: 'Australia', flag: '🇦🇺', code: 'AU', dialCode: '+61'),
  CountryInfo(name: 'Austria', flag: '🇦🇹', code: 'AT', dialCode: '+43'),
  CountryInfo(name: 'Azerbaijan', flag: '🇦🇿', code: 'AZ', dialCode: '+994'),
  CountryInfo(name: 'Bahamas', flag: '🇧🇸', code: 'BS', dialCode: '+1'),
  CountryInfo(name: 'Bahrain', flag: '🇧🇭', code: 'BH', dialCode: '+973'),
  CountryInfo(name: 'Bangladesh', flag: '🇧🇩', code: 'BD', dialCode: '+880'),
  CountryInfo(name: 'Barbados', flag: '🇧🇧', code: 'BB', dialCode: '+1'),
  CountryInfo(name: 'Belarus', flag: '🇧🇾', code: 'BY', dialCode: '+375'),
  CountryInfo(name: 'Belgium', flag: '🇧🇪', code: 'BE', dialCode: '+32'),
  CountryInfo(name: 'Belize', flag: '🇧🇿', code: 'BZ', dialCode: '+501'),
  CountryInfo(name: 'Benin', flag: '🇧🇯', code: 'BJ', dialCode: '+229'),
  CountryInfo(name: 'Bermuda', flag: '🇧🇲', code: 'BM', dialCode: '+1'),
  CountryInfo(name: 'Bhutan', flag: '🇧🇹', code: 'BT', dialCode: '+975'),
  CountryInfo(name: 'Bolivia', flag: '🇧🇴', code: 'BO', dialCode: '+591'),
  CountryInfo(name: 'Bosnia & Herzegovina', flag: '🇧🇦', code: 'BA', dialCode: '+387'),
  CountryInfo(name: 'Botswana', flag: '🇧🇼', code: 'BW', dialCode: '+267'),
  CountryInfo(name: 'Brazil', flag: '🇧🇷', code: 'BR', dialCode: '+55'),
  CountryInfo(name: 'Brunei', flag: '🇧🇳', code: 'BN', dialCode: '+673'),
  CountryInfo(name: 'Bulgaria', flag: '🇧🇬', code: 'BG', dialCode: '+359'),
  CountryInfo(name: 'Burkina Faso', flag: '🇧🇫', code: 'BF', dialCode: '+226'),
  CountryInfo(name: 'Burundi', flag: '🇧🇮', code: 'BI', dialCode: '+257'),
  CountryInfo(name: 'Cambodia', flag: '🇰🇭', code: 'KH', dialCode: '+855'),
  CountryInfo(name: 'Cameroon', flag: '🇨🇲', code: 'CM', dialCode: '+237'),
  CountryInfo(name: 'Canada', flag: '🇨🇦', code: 'CA', dialCode: '+1'),
  CountryInfo(name: 'Cape Verde', flag: '🇨🇻', code: 'CV', dialCode: '+238'),
  CountryInfo(name: 'Cayman Islands', flag: '🇰🇾', code: 'KY', dialCode: '+1'),
  CountryInfo(name: 'Chad', flag: '🇹🇩', code: 'TD', dialCode: '+235'),
  CountryInfo(name: 'Chile', flag: '🇨🇱', code: 'CL', dialCode: '+56'),
  CountryInfo(name: 'China', flag: '🇨🇳', code: 'CN', dialCode: '+86'),
  CountryInfo(name: 'Colombia', flag: '🇨🇴', code: 'CO', dialCode: '+57'),
  CountryInfo(name: 'Comoros', flag: '🇰🇲', code: 'KM', dialCode: '+269'),
  CountryInfo(name: 'Congo', flag: '🇨🇬', code: 'CG', dialCode: '+242'),
  CountryInfo(name: 'Costa Rica', flag: '🇨🇷', code: 'CR', dialCode: '+506'),
  CountryInfo(name: 'Croatia', flag: '🇭🇷', code: 'HR', dialCode: '+385'),
  CountryInfo(name: 'Cuba', flag: '🇨🇺', code: 'CU', dialCode: '+53'),
  CountryInfo(name: 'Cyprus', flag: '🇨🇾', code: 'CY', dialCode: '+357'),
  CountryInfo(name: 'Czech Republic', flag: '🇨🇿', code: 'CZ', dialCode: '+420'),
  CountryInfo(name: 'Denmark', flag: '🇩🇰', code: 'DK', dialCode: '+45'),
  CountryInfo(name: 'Djibouti', flag: '🇩🇯', code: 'DJ', dialCode: '+253'),
  CountryInfo(name: 'Dominica', flag: '🇩🇲', code: 'DM', dialCode: '+1'),
  CountryInfo(name: 'Dominican Republic', flag: '🇩🇴', code: 'DO', dialCode: '+1'),
  CountryInfo(name: 'Ecuador', flag: '🇪🇨', code: 'EC', dialCode: '+593'),
  CountryInfo(name: 'Egypt', flag: '🇪🇬', code: 'EG', dialCode: '+20'),
  CountryInfo(name: 'El Salvador', flag: '🇸🇻', code: 'SV', dialCode: '+503'),
  CountryInfo(name: 'Equatorial Guinea', flag: '🇬🇶', code: 'GQ', dialCode: '+240'),
  CountryInfo(name: 'Eritrea', flag: '🇪🇷', code: 'ER', dialCode: '+291'),
  CountryInfo(name: 'Estonia', flag: '🇪🇪', code: 'EE', dialCode: '+372'),
  CountryInfo(name: 'Ethiopia', flag: '🇪🇹', code: 'ET', dialCode: '+251'),
  CountryInfo(name: 'Fiji', flag: '🇫🇯', code: 'FJ', dialCode: '+679'),
  CountryInfo(name: 'Finland', flag: '🇫🇮', code: 'FI', dialCode: '+358'),
  CountryInfo(name: 'France', flag: '🇫🇷', code: 'FR', dialCode: '+33'),
  CountryInfo(name: 'Gabon', flag: '🇬🇦', code: 'GA', dialCode: '+241'),
  CountryInfo(name: 'Gambia', flag: '🇬🇲', code: 'GM', dialCode: '+220'),
  CountryInfo(name: 'Georgia', flag: '🇬🇪', code: 'GE', dialCode: '+995'),
  CountryInfo(name: 'Germany', flag: '🇩🇪', code: 'DE', dialCode: '+49'),
  CountryInfo(name: 'Ghana', flag: '🇬🇭', code: 'GH', dialCode: '+233'),
  CountryInfo(name: 'Gibraltar', flag: '🇬🇮', code: 'GI', dialCode: '+350'),
  CountryInfo(name: 'Greece', flag: '🇬🇷', code: 'GR', dialCode: '+30'),
  CountryInfo(name: 'Greenland', flag: '🇬🇱', code: 'GL', dialCode: '+299'),
  CountryInfo(name: 'Grenada', flag: '🇬🇩', code: 'GD', dialCode: '+1'),
  CountryInfo(name: 'Guatemala', flag: '🇬🇹', code: 'GT', dialCode: '+502'),
  CountryInfo(name: 'Guinea', flag: '🇬🇳', code: 'GN', dialCode: '+224'),
  CountryInfo(name: 'Guyana', flag: '🇬🇾', code: 'GY', dialCode: '+592'),
  CountryInfo(name: 'Haiti', flag: '🇭🇹', code: 'HT', dialCode: '+509'),
  CountryInfo(name: 'Honduras', flag: '🇭🇳', code: 'HN', dialCode: '+504'),
  CountryInfo(name: 'Hong Kong', flag: '🇭🇰', code: 'HK', dialCode: '+852'),
  CountryInfo(name: 'Hungary', flag: '🇭🇺', code: 'HU', dialCode: '+36'),
  CountryInfo(name: 'Iceland', flag: '🇮🇸', code: 'IS', dialCode: '+354'),
  CountryInfo(name: 'India', flag: '🇮🇳', code: 'IN', dialCode: '+91'),
  CountryInfo(name: 'Indonesia', flag: '🇮🇩', code: 'ID', dialCode: '+62'),
  CountryInfo(name: 'Iran', flag: '🇮🇷', code: 'IR', dialCode: '+98'),
  CountryInfo(name: 'Iraq', flag: '🇮🇶', code: 'IQ', dialCode: '+964'),
  CountryInfo(name: 'Ireland', flag: '🇮🇪', code: 'IE', dialCode: '+353'),
  CountryInfo(name: 'Israel', flag: '🇮🇱', code: 'IL', dialCode: '+972'),
  CountryInfo(name: 'Italy', flag: '🇮🇹', code: 'IT', dialCode: '+39'),
  CountryInfo(name: 'Ivory Coast', flag: '🇨🇮', code: 'CI', dialCode: '+225'),
  CountryInfo(name: 'Jamaica', flag: '🇯🇲', code: 'JM', dialCode: '+1'),
  CountryInfo(name: 'Japan', flag: '🇯🇵', code: 'JP', dialCode: '+81'),
  CountryInfo(name: 'Jordan', flag: '🇯🇴', code: 'JO', dialCode: '+962'),
  CountryInfo(name: 'Kazakhstan', flag: '🇰🇿', code: 'KZ', dialCode: '+7'),
  CountryInfo(name: 'Kenya', flag: '🇰🇪', code: 'KE', dialCode: '+254'),
  CountryInfo(name: 'Kiribati', flag: '🇰🇮', code: 'KI', dialCode: '+686'),
  CountryInfo(name: 'Kuwait', flag: '🇰🇼', code: 'KW', dialCode: '+965'),
  CountryInfo(name: 'Kyrgyzstan', flag: '🇰🇬', code: 'KG', dialCode: '+996'),
  CountryInfo(name: 'Laos', flag: '🇱🇦', code: 'LA', dialCode: '+856'),
  CountryInfo(name: 'Latvia', flag: '🇱🇻', code: 'LV', dialCode: '+371'),
  CountryInfo(name: 'Lebanon', flag: '🇱🇧', code: 'LB', dialCode: '+961'),
  CountryInfo(name: 'Lesotho', flag: '🇱🇸', code: 'LS', dialCode: '+266'),
  CountryInfo(name: 'Liberia', flag: '🇱🇷', code: 'LR', dialCode: '+231'),
  CountryInfo(name: 'Libya', flag: '🇱🇾', code: 'LY', dialCode: '+218'),
  CountryInfo(name: 'Liechtenstein', flag: '🇱🇮', code: 'LI', dialCode: '+423'),
  CountryInfo(name: 'Lithuania', flag: '🇱🇹', code: 'LT', dialCode: '+370'),
  CountryInfo(name: 'Luxembourg', flag: '🇱🇺', code: 'LU', dialCode: '+352'),
  CountryInfo(name: 'Macao', flag: '🇲🇴', code: 'MO', dialCode: '+853'),
  CountryInfo(name: 'Macedonia', flag: '🇲🇰', code: 'MK', dialCode: '+389'),
  CountryInfo(name: 'Madagascar', flag: '🇲🇬', code: 'MG', dialCode: '+261'),
  CountryInfo(name: 'Malawi', flag: '🇲🇼', code: 'MW', dialCode: '+265'),
  CountryInfo(name: 'Malaysia', flag: '🇲🇾', code: 'MY', dialCode: '+60'),
  CountryInfo(name: 'Maldives', flag: '🇲🇻', code: 'MV', dialCode: '+960'),
  CountryInfo(name: 'Mali', flag: '🇲🇱', code: 'ML', dialCode: '+223'),
  CountryInfo(name: 'Malta', flag: '🇲🇹', code: 'MT', dialCode: '+356'),
  CountryInfo(name: 'Marshall Islands', flag: '🇲🇭', code: 'MH', dialCode: '+692'),
  CountryInfo(name: 'Mauritania', flag: '🇲🇷', code: 'MR', dialCode: '+222'),
  CountryInfo(name: 'Mauritius', flag: '🇲🇺', code: 'MU', dialCode: '+230'),
  CountryInfo(name: 'Mexico', flag: '🇲🇽', code: 'MX', dialCode: '+52'),
  CountryInfo(name: 'Micronesia', flag: '🇫🇲', code: 'FM', dialCode: '+691'),
  CountryInfo(name: 'Moldova', flag: '🇲🇩', code: 'MD', dialCode: '+373'),
  CountryInfo(name: 'Monaco', flag: '🇲🇨', code: 'MC', dialCode: '+377'),
  CountryInfo(name: 'Mongolia', flag: '🇲🇳', code: 'MN', dialCode: '+976'),
  CountryInfo(name: 'Montenegro', flag: '🇲🇪', code: 'ME', dialCode: '+382'),
  CountryInfo(name: 'Montserrat', flag: '🇲🇸', code: 'MS', dialCode: '+1'),
  CountryInfo(name: 'Morocco', flag: '🇲🇦', code: 'MA', dialCode: '+212'),
  CountryInfo(name: 'Mozambique', flag: '🇲🇿', code: 'MZ', dialCode: '+258'),
  CountryInfo(name: 'Myanmar', flag: '🇲🇲', code: 'MM', dialCode: '+95'),
  CountryInfo(name: 'Namibia', flag: '🇳🇦', code: 'NA', dialCode: '+264'),
  CountryInfo(name: 'Nauru', flag: '🇳🇷', code: 'NR', dialCode: '+674'),
  CountryInfo(name: 'Nepal', flag: '🇳🇵', code: 'NP', dialCode: '+977'),
  CountryInfo(name: 'Netherlands', flag: '🇳🇱', code: 'NL', dialCode: '+31'),
  CountryInfo(name: 'New Zealand', flag: '🇳🇿', code: 'NZ', dialCode: '+64'),
  CountryInfo(name: 'Nicaragua', flag: '🇳🇮', code: 'NI', dialCode: '+505'),
  CountryInfo(name: 'Niger', flag: '🇳🇪', code: 'NE', dialCode: '+227'),
  CountryInfo(name: 'Nigeria', flag: '🇳🇬', code: 'NG', dialCode: '+234'),
  CountryInfo(name: 'North Korea', flag: '🇰🇵', code: 'KP', dialCode: '+850'),
  CountryInfo(name: 'Norway', flag: '🇳🇴', code: 'NO', dialCode: '+47'),
  CountryInfo(name: 'Oman', flag: '🇴🇲', code: 'OM', dialCode: '+968'),
  CountryInfo(name: 'Pakistan', flag: '🇵🇰', code: 'PK', dialCode: '+92'),
  CountryInfo(name: 'Palau', flag: '🇵🇼', code: 'PW', dialCode: '+680'),
  CountryInfo(name: 'Palestine', flag: '🇵🇸', code: 'PS', dialCode: '+970'),
  CountryInfo(name: 'Panama', flag: '🇵🇦', code: 'PA', dialCode: '+507'),
  CountryInfo(name: 'Papua New Guinea', flag: '🇵🇬', code: 'PG', dialCode: '+675'),
  CountryInfo(name: 'Paraguay', flag: '🇵🇾', code: 'PY', dialCode: '+595'),
  CountryInfo(name: 'Peru', flag: '🇵🇪', code: 'PE', dialCode: '+51'),
  CountryInfo(name: 'Philippines', flag: '🇵🇭', code: 'PH', dialCode: '+63'),
  CountryInfo(name: 'Poland', flag: '🇵🇱', code: 'PL', dialCode: '+48'),
  CountryInfo(name: 'Portugal', flag: '🇵🇹', code: 'PT', dialCode: '+351'),
  CountryInfo(name: 'Puerto Rico', flag: '🇵🇷', code: 'PR', dialCode: '+1'),
  CountryInfo(name: 'Qatar', flag: '🇶🇦', code: 'QA', dialCode: '+974'),
  CountryInfo(name: 'Romania', flag: '🇷🇴', code: 'RO', dialCode: '+40'),
  CountryInfo(name: 'Russia', flag: '🇷🇺', code: 'RU', dialCode: '+7'),
  CountryInfo(name: 'Rwanda', flag: '🇷🇼', code: 'RW', dialCode: '+250'),
  CountryInfo(name: 'Saint Kitts & Nevis', flag: '🇰🇳', code: 'KN', dialCode: '+1'),
  CountryInfo(name: 'Saint Lucia', flag: '🇱🇨', code: 'LC', dialCode: '+1'),
  CountryInfo(name: 'Saint Vincent & Grenadines', flag: '🇻🇨', code: 'VC', dialCode: '+1'),
  CountryInfo(name: 'Samoa', flag: '🇼🇸', code: 'WS', dialCode: '+685'),
  CountryInfo(name: 'San Marino', flag: '🇸🇲', code: 'SM', dialCode: '+378'),
  CountryInfo(name: 'Sao Tome & Principe', flag: '🇸🇹', code: 'ST', dialCode: '+239'),
  CountryInfo(name: 'Saudi Arabia', flag: '🇸🇦', code: 'SA', dialCode: '+966'),
  CountryInfo(name: 'Senegal', flag: '🇸🇳', code: 'SN', dialCode: '+221'),
  CountryInfo(name: 'Serbia', flag: '🇷🇸', code: 'RS', dialCode: '+381'),
  CountryInfo(name: 'Seychelles', flag: '🇸🇨', code: 'SC', dialCode: '+248'),
  CountryInfo(name: 'Sierra Leone', flag: '🇸🇱', code: 'SL', dialCode: '+232'),
  CountryInfo(name: 'Singapore', flag: '🇸🇬', code: 'SG', dialCode: '+65'),
  CountryInfo(name: 'Slovakia', flag: '🇸🇰', code: 'SK', dialCode: '+421'),
  CountryInfo(name: 'Slovenia', flag: '🇸🇮', code: 'SI', dialCode: '+386'),
  CountryInfo(name: 'Solomon Islands', flag: '🇸🇧', code: 'SB', dialCode: '+677'),
  CountryInfo(name: 'Somalia', flag: '🇸🇴', code: 'SO', dialCode: '+252'),
  CountryInfo(name: 'South Africa', flag: '🇿🇦', code: 'ZA', dialCode: '+27'),
  CountryInfo(name: 'South Korea', flag: '🇰🇷', code: 'KR', dialCode: '+82'),
  CountryInfo(name: 'South Sudan', flag: '🇸🇸', code: 'SS', dialCode: '+211'),
  CountryInfo(name: 'Spain', flag: '🇪🇸', code: 'ES', dialCode: '+34'),
  CountryInfo(name: 'Sri Lanka', flag: '🇱🇰', code: 'LK', dialCode: '+94'),
  CountryInfo(name: 'Sudan', flag: '🇸🇩', code: 'SD', dialCode: '+249'),
  CountryInfo(name: 'Suriname', flag: '🇸🇷', code: 'SR', dialCode: '+597'),
  CountryInfo(name: 'Swaziland', flag: '🇸🇿', code: 'SZ', dialCode: '+268'),
  CountryInfo(name: 'Sweden', flag: '🇸🇪', code: 'SE', dialCode: '+46'),
  CountryInfo(name: 'Switzerland', flag: '🇨🇭', code: 'CH', dialCode: '+41'),
  CountryInfo(name: 'Syria', flag: '🇸🇾', code: 'SY', dialCode: '+963'),
  CountryInfo(name: 'Taiwan', flag: '🇹🇼', code: 'TW', dialCode: '+886'),
  CountryInfo(name: 'Tajikistan', flag: '🇹🇯', code: 'TJ', dialCode: '+992'),
  CountryInfo(name: 'Tanzania', flag: '🇹🇿', code: 'TZ', dialCode: '+255'),
  CountryInfo(name: 'Thailand', flag: '🇹🇭', code: 'TH', dialCode: '+66'),
  CountryInfo(name: 'Timor-Leste', flag: '🇹🇱', code: 'TL', dialCode: '+670'),
  CountryInfo(name: 'Togo', flag: '🇹🇬', code: 'TG', dialCode: '+228'),
  CountryInfo(name: 'Tonga', flag: '🇹🇴', code: 'TO', dialCode: '+676'),
  CountryInfo(name: 'Trinidad & Tobago', flag: '🇹🇹', code: 'TT', dialCode: '+1'),
  CountryInfo(name: 'Tunisia', flag: '🇹🇳', code: 'TN', dialCode: '+216'),
  CountryInfo(name: 'Turkey', flag: '🇹🇷', code: 'TR', dialCode: '+90'),
  CountryInfo(name: 'Turkmenistan', flag: '🇹🇲', code: 'TM', dialCode: '+993'),
  CountryInfo(name: 'Turks & Caicos Islands', flag: '🇹🇨', code: 'TC', dialCode: '+1'),
  CountryInfo(name: 'Tuvalu', flag: '🇹🇻', code: 'TV', dialCode: '+688'),
  CountryInfo(name: 'Uganda', flag: '🇺🇬', code: 'UG', dialCode: '+256'),
  CountryInfo(name: 'Ukraine', flag: '🇺🇦', code: 'UA', dialCode: '+380'),
  CountryInfo(name: 'United Arab Emirates', flag: '🇦🇪', code: 'AE', dialCode: '+971'),
  CountryInfo(name: 'United Kingdom', flag: '🇬🇧', code: 'GB', dialCode: '+44'),
  CountryInfo(name: 'United States', flag: '🇺🇸', code: 'US', dialCode: '+1'),
  CountryInfo(name: 'Uruguay', flag: '🇺🇾', code: 'UY', dialCode: '+598'),
  CountryInfo(name: 'Uzbekistan', flag: '🇺🇿', code: 'UZ', dialCode: '+998'),
  CountryInfo(name: 'Vanuatu', flag: '🇻🇺', code: 'VU', dialCode: '+678'),
  CountryInfo(name: 'Venezuela', flag: '🇻🇪', code: 'VE', dialCode: '+58'),
  CountryInfo(name: 'Vietnam', flag: '🇻🇳', code: 'VN', dialCode: '+84'),
  CountryInfo(name: 'Virgin Islands, British', flag: '🇻🇬', code: 'VG', dialCode: '+1'),
  CountryInfo(name: 'Virgin Islands, U.S.', flag: '🇻🇮', code: 'VI', dialCode: '+1'),
  CountryInfo(name: 'Yemen', flag: '🇾🇪', code: 'YE', dialCode: '+967'),
  CountryInfo(name: 'Zambia', flag: '🇿🇲', code: 'ZM', dialCode: '+260'),
  CountryInfo(name: 'Zimbabwe', flag: '🇿🇼', code: 'ZW', dialCode: '+263'),
];
